In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4]

In [5]:
my_array1 = np.array(my_list)

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [8]:
my_lists = [my_list, my_list2]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int32')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
my_zeros_array = np.zeros(5)

In [16]:
my_zeros_array.dtype

dtype('float64')

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arrange(5)