In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.33781401,  0.31744081, -1.57463711,  1.66439155,  1.54071034,
        0.07885157,  1.3040647 ,  0.03865807, -0.7596726 , -1.0908033 ])

In [6]:
B = np.random.randn(10)

In [7]:
B

array([ 1.9559033 , -1.34576617,  0.1443814 , -0.36821653, -0.5787213 ,
       -0.91187233,  2.0474111 ,  1.4848855 ,  0.68791398, -0.19536735])

In [8]:
#Binary Functions
np.add(A, B)

array([ 2.29371731, -1.02832536, -1.43025571,  1.29617502,  0.96198904,
       -0.83302076,  3.3514758 ,  1.52354356, -0.07175862, -1.28617065])

In [9]:
np.maximum(A,B)

array([ 1.9559033 ,  0.31744081,  0.1443814 ,  1.66439155,  1.54071034,
        0.07885157,  2.0474111 ,  1.4848855 ,  0.68791398, -0.19536735])

In [10]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True