In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
 np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1, ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])


In [14]:
dframe1

X         Y         Z
0  0.084331 -0.154535 -0.003756
1  0.059216  0.471231  0.435648
2  0.092509 -0.617462 -1.779265
3  0.154680  0.367818  0.617699

In [15]:
dframe2

Y         Q         X
0  1.149318 -0.009038 -0.296756
1  0.942885  2.895711 -0.077929
2  2.487503  2.289439  0.050293

In [16]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN  0.084331 -0.154535 -0.003756
1       NaN  0.059216  0.471231  0.435648
2       NaN  0.092509 -0.617462 -1.779265
3       NaN  0.154680  0.367818  0.617699
0 -0.009038 -0.296756  1.149318       NaN
1  2.895711 -0.077929  0.942885       NaN
2  2.289439  0.050293  2.487503       NaN

In [17]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.084331 -0.154535 -0.003756
1       NaN  0.059216  0.471231  0.435648
2       NaN  0.092509 -0.617462 -1.779265
3       NaN  0.154680  0.367818  0.617699
4 -0.009038 -0.296756  1.149318       NaN
5  2.895711 -0.077929  0.942885       NaN
6  2.289439  0.050293  2.487503       NaN